name: NextJS build test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Run build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Build NextJS project
        run: npm run build
